/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_ajout (void)
{
  GtkWidget *fenetre_ajout;
  GtkWidget *fixed1;
  GtkWidget *Nom_hotel;
  GtkWidget *adresse;
  GtkWidget *num_responsable;
  GtkObject *etoiles_adj;
  GtkWidget *etoiles;
  GtkWidget *Nom_hotel1;
  GtkWidget *adresse1;
  GtkWidget *Etoiles1;
  GtkWidget *label4;
  GtkWidget *label9;
  GtkWidget *valider;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label11;
  GtkWidget *affiche;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label12;
  GtkWidget *label10;
  GtkWidget *button2;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label16;
  GtkWidget *image7;

  fenetre_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_ajout, 500, 400);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajout), _("fenetre_ajout"));
  gtk_window_set_default_size (GTK_WINDOW (fenetre_ajout), 700, 400);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_ajout), fixed1);
  gtk_widget_set_size_request (fixed1, 500, 400);

  image7 = create_pixmap (fenetre_ajout,"palace.jpg");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed1), image7, 0, 0);
  gtk_widget_set_size_request (image7, 700, 400);

  Nom_hotel = gtk_entry_new ();
  gtk_widget_show (Nom_hotel);
  gtk_fixed_put (GTK_FIXED (fixed1), Nom_hotel, 248, 104);
  gtk_widget_set_size_request (Nom_hotel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Nom_hotel), 8226);

  adresse = gtk_entry_new ();
  gtk_widget_show (adresse);
  gtk_fixed_put (GTK_FIXED (fixed1), adresse, 248, 152);
  gtk_widget_set_size_request (adresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adresse), 8226);

  num_responsable = gtk_entry_new ();
  gtk_widget_show (num_responsable);
  gtk_fixed_put (GTK_FIXED (fixed1), num_responsable, 248, 272);
  gtk_widget_set_size_request (num_responsable, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (num_responsable), 8226);

  etoiles_adj = gtk_adjustment_new (3, 3, 5, 1, 10, 10);
  etoiles = gtk_spin_button_new (GTK_ADJUSTMENT (etoiles_adj), 1, 0);
  gtk_widget_show (etoiles);
  gtk_fixed_put (GTK_FIXED (fixed1), etoiles, 248, 208);
  gtk_widget_set_size_request (etoiles, 60, 27);

  Nom_hotel1 = gtk_label_new (_("<span foreground=\"white\"><i><b> Nom de l'hotel :</b></i></span>"));
  gtk_widget_show (Nom_hotel1);
  gtk_fixed_put (GTK_FIXED (fixed1), Nom_hotel1, 70, 104);
  gtk_widget_set_size_request (Nom_hotel1, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (Nom_hotel1), TRUE);

  adresse1 = gtk_label_new (_("<span foreground=\"white\"><i><b> Adresse : </b></i></span>"));
  gtk_widget_show (adresse1);
  gtk_fixed_put (GTK_FIXED (fixed1), adresse1, 70, 160);
  gtk_widget_set_size_request (adresse1, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (adresse1), TRUE);

  Etoiles1 = gtk_label_new (_("<span foreground=\"white\"><i><b> Etoiles : </b></i></span>"));
  gtk_widget_show (Etoiles1);
  gtk_fixed_put (GTK_FIXED (fixed1), Etoiles1, 70, 216);
  gtk_widget_set_size_request (Etoiles1, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (Etoiles1), TRUE);

  label4 = gtk_label_new (_("<span foreground=\"white\"><i><b>Num\303\251ro du responsable :</b></i></span>"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 70, 272);
  gtk_widget_set_size_request (label4, 176, 32);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  label9 = gtk_label_new (_("<span foreground=\"blue\"size=\"x-large\"><i><b> Ajouter un hotel : </b> </i></span>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 100, 70);
  gtk_widget_set_size_request (label9, 200, 24);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);


  valider = gtk_button_new ();
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed1), valider, 448, 152);
  gtk_widget_set_size_request (valider, 88, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (valider), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox1), label11, FALSE, FALSE, 0);

  affiche = gtk_button_new ();
  gtk_widget_show (affiche);
  gtk_fixed_put (GTK_FIXED (fixed1), affiche, 448, 216);
  gtk_widget_set_size_request (affiche, 88, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (affiche), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  label10 = gtk_label_new (_("<span foreground=\"red\"size=\"xx-large\"><i><b> Espace Agent Hotel : </b></i></span>"));
//(_("<span foreground=\"red\"><i>Num\303\251ro du responsable :</i></span>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 200, 8);
  gtk_widget_set_size_request (label10, 300, 32);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 264, 328);
  gtk_widget_set_size_request (button2, 96, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button2), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox6), label16, FALSE, FALSE, 0);

  

  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) affiche, "clicked",
                    G_CALLBACK (on_affiche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajout, fenetre_ajout, "fenetre_ajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, Nom_hotel, "Nom_hotel");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, adresse, "adresse");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, num_responsable, "num_responsable");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, etoiles, "etoiles");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, Nom_hotel1, "Nom_hotel1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, adresse1, "adresse1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, Etoiles1, "Etoiles1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label9, "label9");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, valider, "valider");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label11, "label11");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, affiche, "affiche");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image2, "image2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label12, "label12");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label10, "label10");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, button2, "button2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image6, "image6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label16, "label16");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image7, "image7");

  return fenetre_ajout;
}

GtkWidget*
create_fenetre_afficher (void)
{
  GtkWidget *fenetre_afficher;
  GtkWidget *fixed2;
  GtkWidget *label8;
  GtkWidget *retour;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label13;
  GtkWidget *supprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label14;
  GtkWidget *modf;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label15;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;

  fenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_afficher, 700, 400);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher), _("fenetre_afficher"));
  gtk_window_set_default_size (GTK_WINDOW (fenetre_afficher), 800, 400);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher), fixed2);
  gtk_widget_set_size_request (fixed2, 700, 700);

  label8 = gtk_label_new (_("<span foreground=\"red\"size=\"xx-large\"><i><b> Liste des hotels : </b></i></span>"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 200, 8);
  gtk_widget_set_size_request (label8, 300, 32);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed2), retour, 496, 352);
  gtk_widget_set_size_request (retour, 128, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (retour), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), supprimer, 16, 96);
  gtk_widget_set_size_request (supprimer, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox4), label14, FALSE, FALSE, 0);

  modf = gtk_button_new ();
  gtk_widget_show (modf);
  gtk_fixed_put (GTK_FIXED (fixed2), modf, 16, 160);
  gtk_widget_set_size_request (modf, 106, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (modf), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox5), label15, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1, 138, 64);
  gtk_widget_set_size_request (scrolledwindow1, 510, 278);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 510, 278);

  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) modf, "clicked",
                    G_CALLBACK (on_modf_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label8, "label8");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, retour, "retour");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label13, "label13");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image4, "image4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label14, "label14");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, modf, "modf");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image5, "image5");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label15, "label15");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, treeview1, "treeview1");

  return fenetre_afficher;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed4;
  GtkWidget *label18;
  GtkWidget *dialog_action_area2;
  GtkWidget *closebutton2;

  dialog2 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog2), _("dialog2"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog2), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog2), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed4, TRUE, TRUE, 0);

  label18 = gtk_label_new (_("Remplir les cases tout d'abord!!!"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 48, 48);
  gtk_widget_set_size_request (label18, 216, 56);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  closebutton2 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), closebutton2, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton2, "clicked",
                    G_CALLBACK (on_closebutton2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (dialog2, label18, "label18");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, closebutton2, "closebutton2");

  return dialog2;
}

