/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Interface_agent (void)
{
  GtkWidget *Interface_agent;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *label7;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label13;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label14;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *entry3;
  GtkWidget *label15;
  GtkWidget *combobox1;
  GtkWidget *label16;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button1;
  GtkWidget *label1;
  GtkWidget *fixed2;
  GtkWidget *label17;
  GtkWidget *entry4;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *label22;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkObject *spinbutton13_adj;
  GtkWidget *spinbutton13;
  GtkWidget *label23;
  GtkWidget *entry5;
  GtkWidget *button4;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label24;
  GtkWidget *button5;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label25;
  GtkWidget *button6;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label26;
  GtkWidget *label2;
  GtkWidget *empty_notebook_page;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;

  Interface_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Interface_agent), _("Interface-agent"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (Interface_agent), notebook1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  label7 = gtk_label_new (_("depart de :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 32, 56);
  gtk_widget_set_size_request (label7, 104, 40);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 136, 64);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 488, 64);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label8 = gtk_label_new (_("Arriv\303\251e \303\240 :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 368, 64);
  gtk_widget_set_size_request (label8, 80, 32);

  label9 = gtk_label_new (_("Date de depart :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 24, 136);
  gtk_widget_set_size_request (label9, 128, 48);

  label10 = gtk_label_new (_("Jour"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 256, 112);
  gtk_widget_set_size_request (label10, 49, 17);

  label11 = gtk_label_new (_("Mois"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 376, 112);
  gtk_widget_set_size_request (label11, 49, 17);

  label12 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 496, 112);
  gtk_widget_set_size_request (label12, 49, 17);

  spinbutton1_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1, 256, 152);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton2, 368, 152);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (2019, 2019, 2030, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton3, 496, 152);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label13 = gtk_label_new (_("Date d'arriv\303\251e :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed1), label13, 32, 216);
  gtk_widget_set_size_request (label13, 112, 40);

  spinbutton4_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton4, 256, 224);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton5, 368, 224);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (2019, 2019, 2030, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton6, 496, 224);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label14 = gtk_label_new (_("Date/h :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed1), label14, 40, 296);
  gtk_widget_set_size_request (label14, 80, 32);

  spinbutton7_adj = gtk_adjustment_new (1, 0, 23, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton7, 176, 304);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 464, 304);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label15 = gtk_label_new (_("Prix/\342\202\254 :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed1), label15, 344, 304);
  gtk_widget_set_size_request (label15, 64, 24);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox1, 208, 384);
  gtk_widget_set_size_request (combobox1, 170, 40);

  label16 = gtk_label_new (_("Classe :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed1), label16, 56, 384);
  gtk_widget_set_size_request (label16, 72, 32);

  button2 = gtk_button_new_with_mnemonic (_("Appliquer"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 320, 464);
  gtk_widget_set_size_request (button2, 88, 37);

  button3 = gtk_button_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 544, 464);
  gtk_widget_set_size_request (button3, 88, 40);

  button1 = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 88, 464);
  gtk_widget_set_size_request (button1, 88, 40);

  label1 = gtk_label_new (_("Vols"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  label17 = gtk_label_new (_("Destination :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 48, 64);
  gtk_widget_set_size_request (label17, 112, 48);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 176, 72);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  spinbutton8_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton8, 192, 168);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  spinbutton9_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton9, 304, 168);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  spinbutton10_adj = gtk_adjustment_new (2019, 2019, 2030, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton10, 424, 168);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  label18 = gtk_label_new (_("Date de d\303\251part :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 32, 160);
  gtk_widget_set_size_request (label18, 128, 40);

  label19 = gtk_label_new (_("Jour"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed2), label19, 192, 128);
  gtk_widget_set_size_request (label19, 49, 17);

  label21 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 424, 128);
  gtk_widget_set_size_request (label21, 49, 17);

  label20 = gtk_label_new (_("Mois"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed2), label20, 304, 128);
  gtk_widget_set_size_request (label20, 49, 17);

  label22 = gtk_label_new (_("Date d'arriv\303\251e :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 32, 232);
  gtk_widget_set_size_request (label22, 120, 48);

  spinbutton11_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton11, 192, 240);
  gtk_widget_set_size_request (spinbutton11, 60, 27);

  spinbutton12_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton12, 304, 240);
  gtk_widget_set_size_request (spinbutton12, 60, 27);

  spinbutton13_adj = gtk_adjustment_new (2019, 2019, 2030, 1, 10, 10);
  spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton13_adj), 1, 0);
  gtk_widget_show (spinbutton13);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton13, 424, 240);
  gtk_widget_set_size_request (spinbutton13, 60, 27);

  label23 = gtk_label_new (_("Prix/\342\202\254 :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 48, 312);
  gtk_widget_set_size_request (label23, 80, 32);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 168, 320);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 248, 424);
  gtk_widget_set_size_request (button4, 104, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button4), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox1), label24, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 440, 424);
  gtk_widget_set_size_request (button5, 112, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button5), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Modifier "));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox2), label25, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 80, 424);
  gtk_widget_set_size_request (button6, 112, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button6), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox3), label26, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("Excursions"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label3 = gtk_label_new (_("Voitures"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label4 = gtk_label_new (_("Hotels"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label5 = gtk_label_new (_("Factures"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label5);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label6 = gtk_label_new (_("Reclamations"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label6);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Interface_agent, Interface_agent, "Interface_agent");
  GLADE_HOOKUP_OBJECT (Interface_agent, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Interface_agent, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Interface_agent, label7, "label7");
  GLADE_HOOKUP_OBJECT (Interface_agent, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Interface_agent, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Interface_agent, label8, "label8");
  GLADE_HOOKUP_OBJECT (Interface_agent, label9, "label9");
  GLADE_HOOKUP_OBJECT (Interface_agent, label10, "label10");
  GLADE_HOOKUP_OBJECT (Interface_agent, label11, "label11");
  GLADE_HOOKUP_OBJECT (Interface_agent, label12, "label12");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Interface_agent, label13, "label13");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (Interface_agent, label14, "label14");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (Interface_agent, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Interface_agent, label15, "label15");
  GLADE_HOOKUP_OBJECT (Interface_agent, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (Interface_agent, label16, "label16");
  GLADE_HOOKUP_OBJECT (Interface_agent, button2, "button2");
  GLADE_HOOKUP_OBJECT (Interface_agent, button3, "button3");
  GLADE_HOOKUP_OBJECT (Interface_agent, button1, "button1");
  GLADE_HOOKUP_OBJECT (Interface_agent, label1, "label1");
  GLADE_HOOKUP_OBJECT (Interface_agent, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Interface_agent, label17, "label17");
  GLADE_HOOKUP_OBJECT (Interface_agent, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (Interface_agent, label18, "label18");
  GLADE_HOOKUP_OBJECT (Interface_agent, label19, "label19");
  GLADE_HOOKUP_OBJECT (Interface_agent, label21, "label21");
  GLADE_HOOKUP_OBJECT (Interface_agent, label20, "label20");
  GLADE_HOOKUP_OBJECT (Interface_agent, label22, "label22");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (Interface_agent, spinbutton13, "spinbutton13");
  GLADE_HOOKUP_OBJECT (Interface_agent, label23, "label23");
  GLADE_HOOKUP_OBJECT (Interface_agent, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Interface_agent, button4, "button4");
  GLADE_HOOKUP_OBJECT (Interface_agent, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Interface_agent, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Interface_agent, image1, "image1");
  GLADE_HOOKUP_OBJECT (Interface_agent, label24, "label24");
  GLADE_HOOKUP_OBJECT (Interface_agent, button5, "button5");
  GLADE_HOOKUP_OBJECT (Interface_agent, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Interface_agent, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Interface_agent, image2, "image2");
  GLADE_HOOKUP_OBJECT (Interface_agent, label25, "label25");
  GLADE_HOOKUP_OBJECT (Interface_agent, button6, "button6");
  GLADE_HOOKUP_OBJECT (Interface_agent, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Interface_agent, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Interface_agent, image3, "image3");
  GLADE_HOOKUP_OBJECT (Interface_agent, label26, "label26");
  GLADE_HOOKUP_OBJECT (Interface_agent, label2, "label2");
  GLADE_HOOKUP_OBJECT (Interface_agent, label3, "label3");
  GLADE_HOOKUP_OBJECT (Interface_agent, label4, "label4");
  GLADE_HOOKUP_OBJECT (Interface_agent, label5, "label5");
  GLADE_HOOKUP_OBJECT (Interface_agent, label6, "label6");

  return Interface_agent;
}

